import test from 'node:test';
import assert from 'node:assert/strict';

import {
  getAutoGeneratedSlugUpdate,
  getSubmitSlug,
} from './blogSlugState.mjs';

test('auto-generates a slug for a new post only when the slug is empty and unedited', () => {
  assert.deepEqual(
    getAutoGeneratedSlugUpdate({ title: 'Student Finance Guide 2026', slug: '' }, false),
    { title: 'Student Finance Guide 2026', slug: 'student-finance-guide-2026' }
  );
});

test('does not auto-change an existing slug when the title changes', () => {
  const form = {
    title: 'A Better SEO Title',
    slug: 'original-url-slug',
  };

  assert.equal(getAutoGeneratedSlugUpdate(form, false), form);
});

test('does not auto-change slug after the user has edited the slug field', () => {
  const form = {
    title: 'A Better SEO Title',
    slug: '',
  };

  assert.equal(getAutoGeneratedSlugUpdate(form, true), form);
});

test('keeps edit-mode loaded slugs untouched even when title differs from slug', () => {
  const form = {
    title: 'Updated Admissions Advice',
    slug: 'legacy-admissions-url',
  };

  assert.equal(getAutoGeneratedSlugUpdate(form, true), form);
});

test('submit slug falls back to title only while slug remains unedited', () => {
  assert.equal(getSubmitSlug({ slug: '', title: 'Fresh Draft' }, false), 'fresh-draft');
  assert.equal(getSubmitSlug({ slug: '', title: 'Fresh Draft' }, true), '');
  assert.equal(getSubmitSlug({ slug: ' custom-url ', title: 'Fresh Draft' }, true), 'custom-url');
});
