function fallbackSlugify(value = '') {
  return value
    .toString()
    .toLowerCase()
    .trim()
    .replace(/['’]/g, '')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 120);
}

export function getAutoGeneratedSlugUpdate(form, isSlugEdited, createSlug = fallbackSlugify) {
  if (isSlugEdited || String(form.slug || '').trim()) {
    return form;
  }

  const nextSlug = createSlug(form.title);
  if (!nextSlug) {
    return form;
  }

  return {
    ...form,
    slug: nextSlug,
  };
}

export function getSubmitSlug(form, isSlugEdited, createSlug = fallbackSlugify) {
  const currentSlug = String(form.slug || '').trim();
  if (currentSlug) {
    return currentSlug;
  }

  return isSlugEdited ? '' : createSlug(form.title);
}
